export const ProgramLocalOptions = [
    { label: 'Remoto', value: 'REMOTE' },
    { label: 'Acre', value: 'AC' },
    // complete value label with Brazilian states
    { label: 'Alagoas', value: 'AL' },
    { label: 'Amapá', value: 'AP' },
    { label: 'Amazonas', value: 'AM' },
    { label: 'Bahia', value: 'BA' },
    { label: 'Ceará', value: 'CE' },
    { label: 'Distrito Federal', value: 'DF' },
    { label: 'Espírito Santo', value: 'ES' },
    { label: 'Goiás', value: 'GO' },
    { label: 'Maranhão', value: 'MA' },
    { label: 'Mato Grosso', value: 'MT' },
    { label: 'Mato Grosso do Sul', value: 'MS' },
    { label: 'Minas Gerais', value: 'MG' },
    { label: 'Pará', value: 'PA' },
    { label: 'Paraíba', value: 'PB' },
    { label: 'Paraná', value: 'PR' },
    { label: 'Pernambuco', value: 'PE' },
    { label: 'Piauí', value: 'PI' },
    { label: 'Rio de Janeiro', value: 'RJ' },
    { label: 'Rio Grande do Norte', value: 'RN' },
    { label: 'Rio Grande do Sul', value: 'RS' },
    { label: 'Rondônia', value: 'RO' },
    { label: 'Roraima', value: 'RR' },
    { label: 'Santa Catarina', value: 'SC' },
    { label: 'São Paulo', value: 'SP' },
    { label: 'Sergipe', value: 'SE' },
    { label: 'Tocantins', value: 'TO' }

];


export const ProgramLanguageOptions = [
    { value: 'EN', label: 'Inglês' },
    { value: 'PT', label: 'Português' },
    { value: 'FR', label: 'Francês' },
    { value: 'ES', label: 'Espanhol' },
];

export const TagOptions = [
    { value: 'MEDIO', label: 'Ensino Médio' },
    { value: 'SUPERIOR', label: 'Ensino Superior' },
    { value: 'TECNICO', label: 'Ensino Técnico' },
    { value: 'TECNOLOGO', label: 'Ensino Tecnólogo' },
    { value: 'MESTRADO', label: 'Mestrado' },
    { value: 'DOUTORADO', label: 'Doutorado' },
    { value: 'POS_DOUTORADO', label: 'Pós-Doutorado' },
    { value: 'ESPECIALIZACAO', label: 'Especialização' },
    { value: 'MBA', label: 'MBA' },
    { value: 'NOTURNO', label: 'Noturno' },
    { value: 'MATUTINO', label: 'Matutino' },
    { value: 'VESPERTINO', label: 'Vespertino' },
    { value: 'INTEGRAL', label: 'Integral' },
    { value: 'EAD', label: 'EAD' },
    { value: 'PRESENCIAL', label: 'Presencial' },
    { value: 'SEMI_PRESENCIAL', label: 'Semi-Presencial' },
    { value: 'GRATUITO', label: 'Gratuito' },
    { value: 'PAGO', label: 'Pago' },
    { value: 'BOLSAS', label: 'Bolsas' },
    { value: 'FINANCIAMENTO', label: 'Financiamento' },
    { value: 'PROUNI', label: 'Prouni' },
    { value: 'FIES', label: 'Fies' },
    { value: 'ENEM_PREP', label: 'Enem Preparatório' },
];